# Generated by Django 5.0.6 on 2024-07-13 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media-files'),
            preserve_default=False,
        ),
    ]
